version: '3.8'

volumes:
  postgres_data:
    name: postgres_data_dev

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-backend}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'  # Exposed for development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-backend} -d ${DB_NAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - .:/app  # Mount source code for hot reload
      - /app/node_modules  # Don't override node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - db

  migrator:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "npm install prisma --no-save &&
             npx prisma generate &&
             npx prisma migrate dev"  # Use migrate dev instead of deploy
    environment:
      DATABASE_URL: 'postgresql://${DB_USER:-backend}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-backend}'
    depends_on:
      db:
        condition: service_healthy
