volumes:
  postgres:

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '${DB_EXPOSED_PORT-5432}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-backend_user}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  migrator:
    build: .
    environment:
      DATABASE_URL: 'postgresql://${DB_USER:-backend_user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-backend}'
    depends_on:
      db:
        condition: service_healthy
