SET
    client_encoding = 'UTF8';

CREATE ROLE superuser;

ALTER ROLE superuser
WITH
    SUPERUSER CREATEDB NOCREATEROLE NOINHERIT LOGIN REPLICATION;

CREATE ROLE backend
WITH
    LOGIN PASSWORD 'password';

ALTER ROLE backend
WITH
    SUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;

CREATE DATABASE backend;

ALTER DATABASE backend OWNER TO backend;

-- CREATE ROLE front_user;
-- ALTER ROLE front_user WITH NOCREATEDB NOCREATEROLE NOINHERIT LOGIN;
-- CREATE ROLE front_artist;
-- ALTER ROLE front_artist WITH NOCREATEDB NOCREATEROLE NOINHERIT LOGIN;