SET
    client_encoding = 'UTF8';

CREATE ROLE superuser;

ALTER ROLE superuser
WITH
    SUPERUSER CREATEDB NOCREATEROLE NOINHERIT LOGIN REPLICATION;

CREATE ROLE backend
WITH
    LOGIN PASSWORD 'password';

ALTER ROLE backend
WITH
    SUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;

CREATE DATABASE backend;

ALTER DATABASE backend OWNER TO backend;